@echo off
echo Activating radar environment...
call activate radar
echo Starting GUI...
start "" python "startGUI.py"
echo GUI started. Script will close in 3 seconds...
timeout /t 3 /nobreak >nul
exit